ch setup continuous intregration
atlp-rwanda/c2-barefoot-backend pull request #5
Opened 2020-10-08 13:38 UTC by habaumugisha1

# Description

This is for configuring continuous integration such as setting up the test environment on local and running on Travis, coveralls, code climate analysis, and maintainability

Fixes # (issue)
>No issue fixed because it a new feature
## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

>This will be tested by running `npm test`

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-08 14:29 UTC, salviosage requested changes
Nice work, please attend my review

2020-10-08 14:29 UTC, salviosage commented on src/tests/app.test.js
> +    expect('Welcome to Barefoot Nomad').to.equal('Welcome to Barefoot Nomad');
please change this  to `expect(res.text).to.equal('Welcome to Barefoot Nomad');`

2020-10-08 14:29 UTC, salviosage commented on package.json
> +    "test": "nyc --reporter=html --reporter=text mocha --require @babel/register ./src/tests/*.test.js --timeout 1000000 --exit",
you should change environment to test too

2020-10-09 08:48 UTC, salviosage requested changes
Nice work ,I left some comments

2020-10-09 08:48 UTC, salviosage commented on .coveralls.yml
> +repo_token: LBqOgmrFuiVAaGMil54sD40Axr58PJ7kz
this token should come from `.env` file

2020-10-09 08:48 UTC, salviosage commented on .travis.yml
> +
add this `env:
  global:
    - NODE_ENV=test` learn more here [Here](https://docs.travis-ci.com/user/environment-variables/#global-variables)

2020-10-09 08:56 UTC, inezabonte requested changes
Great work. In the`welcome.js` controller you can change the response message to a `json` object to make it easier for testing
```javascript
res.status(200).json({message: 'Welcome to Barefoot Nomad'});
```

2020-10-09 10:43 UTC, inezabonte approved these changes

2020-10-09 13:06 UTC, salviosage commented on .env
> +COVERALLS_REPO_TOKEN=LBqOgmrFuiVAaGMil54sD40Axr58PJ7kz
Please delete this

2020-10-09 13:06 UTC, salviosage commented on .gitignore
> +
you can add .env here

2020-10-09 13:06 UTC, salviosage commented on package.json
> +    "cohort2-barefoot": "nodemon --exec babel-node app.js",
this might be too big instead of `ohort2-barefoot` you can say `dev`

2020-10-09 13:06 UTC, salviosage commented on src/controllers/welcome.js
> +  res.status(200).json({ status: 200, message: 'Welcome to Barefoot Nomad' });
nice work here

2020-10-12 14:03 UTC, salviosage approved these changes
LGTM

2020-10-12 14:29 UTC, inezabonte approved these changes

2020-10-12 16:00 UTC, merged